-- Migration 000175: signing-key provenance (generated vs imported)
--
-- Per-org signing keys are now the default for every organisation (auto-
-- provisioned on first use). key_source distinguishes:
--   • 'generated' — server-held RSA material minted by Clavex; auto-rotatable.
--   • 'imported'  — customer-supplied BYOK / external-custody (HSM) material;
--                   never regenerated by the scheduled rotation worker.
-- Existing rows default to 'generated'; ImportForOrg tags new rows 'imported'.

ALTER TABLE signing_keys
    ADD COLUMN IF NOT EXISTS key_source TEXT NOT NULL DEFAULT 'generated'
        CHECK (key_source IN ('generated', 'imported'));
